language: ruby
rvm:
  - 2.2.5
services:
  - mysql
before_install:
  - PWD=`pwd`
  - "echo '## Installing dependencies'"
  - "sudo apt-get update"
  - "sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi"
  - "echo '## Downloading wkhtmltopdf'"
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - "echo '## Installing wkhtmltox'"
  - "sudo dpkg -i wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - "echo `which wkhtmltopdf`"
before_script:
  - mysql -e 'create database snorby_test;'
  - bundle exec rake db:schema:load RAILS_ENV=test
script:
  - bundle exec rake test
